### ISSUE TITLE
Deployments can't be added

### ISSUE THREAD

**Issue by rlambrec** [gomorpheus/morpheus-cli#10]
Hi,

Either way I am using it wrong or there is an issue with adding deployments.

When I add one, for example 'testadd'.
```
$ morpheus deployments add
Name: testadd
Description (optional): testadd description
Added deployment testadd

Deployment Details
==================

         ID: 10
       Name: testadd
Description: testadd description
   Versions:
    Created: 10/29/20 09:10 AM
    Updated: 10/29/20 09:10 AM

Versions
---------------------

No versions found.
```

Everything works.

Listing sub versions also works (no versions are added yet to my test)
```
$ morpheus deployments list-versions testadd

Deployment Versions | testadd
==================

No versions found.
```

However when I start adding a version, I get an internal 500 server
```
$ morpheus deployments add-version testadd 1
Error Communicating with the remote appliance. 500 Internal Server Error
```

Invoking the interactive cli also doesn't do much
```
$ morpheus deployments add-version testadd
Version: 1

Error Communicating with the remote appliance. 500 Internal Server Error
```

And now a bit with verbose info
```
$ morpheus deployments add-version testadd -V
establishing connection to remote [demo] https://10.5.242.1
GET "https://10.5.242.1/api/deployments?name=testadd", "Accept"=>"*/*", "Accept-Encoding"=>"gzip, deflate", "Authorization"=>"Bearer ************", "User-Agent"=>"morpheus-cli 5.0.2 (linux-gnu x86_64) ruby/2.5.1p57"
# => 200 OK | application/json 242 bytes
Version: 1
GET "https://10.5.242.1/api/options/deployTypes?userVersion=1", "Accept"=>"*/*", "Accept-Encoding"=>"gzip, deflate", "Authorization"=>"Bearer ************", "User-Agent"=>"morpheus-cli 5.0.2 (linux-gnu x86_64) ruby/2.5.1p57"
# => 500 InternalServerError | application/json 62 bytes
Error Communicating with the remote appliance. (HTTP 500)
REQUEST
GET "https://10.5.242.1/api/options/deployTypes?userVersion=1"

RESPONSE
HTTP 500  |  62.00 B
{
  "success": false,
  "msg": "Looks like the server threw a gasket"
}
```

Am I missing some arguments? Because if I am not mistaken just adding a version isn't the complete story.

However when I try
```
pipeline:~$ morpheus deployments add-version testadd 1.0.5 fetch http://test/deploy/file.war
morpheus: too many arguments, expected 0-2 and got 4: testadd, 1.0.5, fetch, http://test/deploy/file.war
```
It confirms me that there should only be two parameters.

I am running against CLI:  version 5.0.2

Kind regards,

**Comment by jamesdickson6** [comment]
Hey @rlambrec 
Sorry for the delayed response!
I haven't been able to reproduce this yet.

My guess is that you have an older version of the appliance and may need to upgrade. You'll need 4.2.4 I believe to use that command.
If you can, send me the error and stacktrace being logged for that 500 error.
The cli can be used to view the appliance logs: `morpheus health logs -a`

Thanks,
- James
email: jdickson@morpheusdata.com

**Comment by rlambrec** [comment]
Yep, that's it. It's broken in version 4.2.3, bumping the version to 4.2.4 fixes the problem.

Thanks
