### ISSUE TITLE
Morpheus CLI connectivity error

### ISSUE THREAD

**Issue by eddiemorphe** [gomorpheus/morpheus-cli#11]
Ever since the upgrade the Morpheus appliance to 5.2.2 we are not able to connect to the remote host:

Error Communicating with the remote appliance. (HTTP 500)

RESPONSE
HTTP 500  |  49.00 B
{
  "error": "server_error",
  "error_description": null

**Comment by jamesdickson6** [comment]
It looks like an issue with existing access tokens being invalid after upgrading from 4.2 to 5.x.
The solution is delete existing tokens. 
You can accomplish this quickly for all users with the following db query:
```
delete from access_token_additional_information;
delete from access_token_scope;
delete from access_token;
```

Alternatively, you can use the UI to clear your current token at: 
Click on your name in the upper right > USER SETTINGS > API ACCESS  > ACTIONS > Clear

**Comment by eddiemorphe** [comment]
Able to fix this by refreshing the API/CLI token from the GUI.

Thanks for responding.


Regards,
Edward

"Creating value that increases customer competitiveness"
