### ISSUE TITLE
Apparent issue around -f fields and --csv / --json in relation to role and group listings in 5.4.5.1

### ISSUE THREAD

**Issue by rjr162** [gomorpheus/morpheus-cli#16]
Client Version: 5.4.5.1

I've noticed an issue around the -f fields flag when using --csv or --json where the name field will return 'null' instead of the actual value.

When you do a 'morpheus roles list -f name,description' things list fine, showing two columns, one for name and one for description with the values for each row displaying properly. The issue appears when you add --csv or --json, the "name" values all become "null"

name          | description                                     
--------------|-------------------------------------------------
Standard User | Should mirror permissions in prod for most users

becomes:
morpheus> roles list -f name,description --csv
name,description
null,Should mirror permissions in prod for most users

or 

morpheus> roles list -f name,description --json
{
  "roles": [
    {
      "name": null,
      "description": "Should mirror permissions in prod for most users"
    },

**Comment by rjr162** [comment]
Looking at some old version I still have lingering, it appears this also occurred in 5.4.4.2 and 5.3.2

**Comment by rjr162** [comment]
This can be closed, resolved as the issue was the default column name if you "roles list" is "NAME", but the actual API field is "authority". If you do
roles list -f authority,description --json
things list fine so the morpheus-cli must be substituting 'authority' in for -f name when not using the --csv or --json flags.

Since the 'name' field natively exists in the 'groups' results from the API, the 'groups list -f name --json/--csv' works as expected

Thanks!

-- Ron

**Comment by jamesdickson6** [comment]
Ah yes, you figured it out. There is some inconsistency in the behavior of the list commands right now that I will get cleaned up soon.  In general, the default table view tries to match the labels of the UI and these do not always match up with the actual property name. You can use `-j` or `--all-options` a  see  the actual properties that are available. It's also possible to select and rename columns in the output, like this: `roles list -f "authority as name,description" --json`
Thanks for bringing this up, we'll try to make it more intuitive.
