### ISSUE TITLE
instances add Skip Agent flag confusing/inconsistent

### ISSUE THREAD

**Issue by rjr162** [gomorpheus/morpheus-cli#18]
I was working on a unit test and was going to use the CLI vs direct python to API to save myself some time, but I noticed the 
Skip Agent Install (yes/no): ?
  * Skip Agent Install [-O config.noAgent=] - 

Option in the CLI is confusing/broken in terms of the -O config.noAgent=

I was using -O config.noAgent=yes to attempt to skip the install as our dev environment isn't accessible from the client VM networks, so we have to skip agent install or builds fail. My build failed with "unable to install agent"

I did some testing with -O config.noAgent=no and that didn't work either, then I realized the cli json output uses:     "noAgent": "off/on", so I tested with -O config.noAgent=on and that worked to successfully skip the agent install.

It may be helpful to match the yes/no to on/off in the ? part for Skip Agent since it's presenting the -O config.noAgent= under "yes"/"no" which don't in fact work with the -O config.noAgent= option

**Comment by jamesdickson6** [comment]
Thanks for the write up.
I've updated the prompting to display on/off instead of yes/no. This will be in the next CLI release (5.5.2).
