### ISSUE TITLE
Newer versions appear to have removed the "custom" option for some global/default role permissions

### ISSUE THREAD

**Issue by rjr162** [gomorpheus/morpheus-cli#19]
I recently updated morpheus-cli to 5.5.3.1 via the 'gem update' and noticed it broke one of our on-boarding scripts.

The issue is the "custom" permission option appears to have been removed from 3 key "global/default" role permissions we use:

Usage: morpheus roles update-default-group-access [role] [access]
No longer appears to accept the access of "custom" that the WebUI allows, and instead lists the access levels of "full, read, or none"

Usage: morpheus roles update-default-catalog-item-type-access [role] [access]
Also no longer appears to accept "custom" and requires "Full or none"

Lastly is Usage: morpheus roles update-default-instance-type-access [role] [access]
This also appears to not like "custom" anymore and instead requires "full or none"

The issue is with those set it appears the individual items under those global roles apparently don't get set as they should and like they use to, with the top level access setting overwriting and preventing adjustment of any sub fields.
The behavior mimics the WebUI, where setting the default to "None" sets all things to none and doens't allow individual item adjustments. Same for the other Read or Full settings, when we need specific custom adjustments of items under say "groups", "instance types", etc.

Can the "custom" flags be added back in as this appears to make the CLI deviate heavily from the role permissions settings capabilities found within the WebUI.

Thanks!

**Comment by rjr162** [comment]
Looking back, it seems this change came about with the renaming of the -global- to -default- conventions, and the "custom" last appeared in 5.5.1.5 and were removed in 5.5.2+

**Comment by rjr162** [comment]
You can ignore. Further looking shows the API settings in 5.2.x+ in Morpheus follow the same pattern, and it just clicked the Morpheus-CLI release is matching those release versions.

I'll downgrade my gem back to a point that matches and supports the required 'custom' option

Thanks!

**Comment by jamesdickson6** [comment]
@rjr162 We will get this resolved so you can update and your old commands will work again. Thanks for bringing it to our attention and the detailed description is greatly appreciated.

**Comment by jamesdickson6** [comment]
This should be fixed in 6.0.0, the command allows `custom` to be passed once again.
