### ISSUE TITLE
Issue with hosts make-managed and the --install-agent off flag

### ISSUE THREAD

**Issue by rjr162** [gomorpheus/morpheus-cli#9]
I'm not sure if this is the expected behavior but the workflow to me suggest this is not:

I'm running the following command:

hosts make-managed test-win2019 --install-agent off --group umg/testing.example --dry-run

This command is prompting for the following:

SSH Username: 
SSH Username: 
SSH Username: f
SSH Password (optional): 
OS Type (optional) ['?' for options]:

This is requiring an SSH username which I believe it should only prompt for if I'm telling it to install the agent (since it would need access into the VM to install this but otherwise no access is required).

The dry-run output shows:

REQUEST
PUT https://test.example.morpheus.install/api/servers/###/install-agent

JSON
{
  "server": {
    "sshUsername": "f",
    "sshPassword": "",
    "provisionSiteId": #
  },
  "installAgent": false
}

What I'm trying to do is script out an semi-automated "convert to manage by reading in config values from a file" to suck in vCenter VMs that aren't currently managed by Morpheus so they are now managed and show within Morpheus properly. It seems the '--install-agent off' isn't suppose to prompt then for the SSH Username and I'm not sure why it's pinging the /install-agent API at that point?

Thanks!

**Comment by jamesdickson6** [comment]
This should be resolved in the next release, version 5.2.0 (today or tomorrow).
The solution for now is to just make the Username prompt optional, not required.
